### ISSUE TITLE
PDF Workflow besides Receipts

### ISSUE THREAD

**Issue by meyerjom** [holtwick/onepile#48]
Hello Dirk,
because you asked for feedback in the software:
My use case for Collect would be to store all the documents in a searchable "database" that do not fit into Receipts because they are not invoices.

The following is not yet clear to me: 
* What does "Level" under Info mean? What function does it have?

I would like to wish the following functions:
* Clear inbox, with new documents which are not yet tagged.
* The possibility to maintain the creation date of the document, best recognized automatically.
* The possibility to maintain a sender of the document, best automatically recognized.
* The possibility to export all documents from a certain sender.
* If documents, after they were transferred from the file system, are moved there directly into suitable subfolders, e.g. into $Tags/$sender.
* The possibility to set how long documents should be kept and when they should be deleted.

I'm not sure if I'm using the software in your sense, but it would cover a big need for me. I would be happy if I could pay money for it (also as a subscription model).

Many thanks and greetings
Johannes

**Comment by holtwick** [comment]
Hi Johannes,

Thanks  for your feedback. 

The `level` is just about visibility. For example if you attach files to notes by dragging the files into the note, it is very likely that you don't want to see those in the primary list level as "new files", because they belong to the note. But in Collect everything is a document that just has relations to other documents. Therefore I introduced these levels. Not sure if this is a super smart idea, this might change in the future if I find a better solution.

Collect in general is different to Receipts, therefore an inbox concept is missing for now. How is your primary way to import new files?

Recognizing contents might come in a future version. These features will have more flexibility than in Receipts.

For expiration date see #32 

All other features describe pretty well where I want to go with Collect ;) The primary goal for now is to mature the existing basic features, therefore your feedback is very much appreciated.

Cheers,
Dirk

**Comment by meyerjom** [comment]
Hi, Dirk, 
Thank you very much for the quick answer. 
Unfortunately I still don't understand the concept of Level completely. It would be best, if the documentation is supplemented on the web page. In my case notes would not play a big role, because I already have a lot of apps for such small memos and I would be afraid that the speed of the "quick note" will suffer when thousands of PDFs are also managed & synchronized with this software. 

Currently, I'm pulling PDFs from the finder into Collect and when I have time, I tag them. Therefore an inbox would support my workflow a lot. The rest sounds exactly like what I'm looking for right now. 
If there's anything I can do to help, please let me know. 

Many greetings 
Johannes

**Comment by holtwick** [comment]
I see, you are more interested in the "document management" than in the "note taking". Indeed there is still some stuff to do before being where https://www.receipts-app.com/ is right now. 

Collect should never get slow, at least that is the plan ;)

Just keep testing and give feedback, that will help me most. Thanks!

**Comment by holtwick** [comment]
I will close this issue for now, but keep the ideas in mind. For the inbox I made this #86 For observed folders this #26
